### ISSUE TITLE
IndexError when trying to install first mod

### ISSUE THREAD

**Issue by kohbo** [Tantrisse/Factorio-mods-manager#8] opened 2021-03-24 19:03 UTC
Starting with a fresh install of the headless factorio, running 

`./mods_manager.py -i LogisticTrainNetwork`

results in the following exception

> Traceback (most recent call last):
>   File "./mods_manager.py", line 764, in <module>
>     sys.exit(main())
>   File "./mods_manager.py", line 736, in main
>     install_mod(args.mod_name_to_install)
>   File "./mods_manager.py", line 409, in install_mod
>     conflict = mod_has_conflicts(dependencies['conflict'])
>   File "./mods_manager.py", line 326, in mod_has_conflicts
>     for mod in read_mods_list():
>   File "./mods_manager.py", line 175, in read_mods_list
>     installed_mods_list.pop(0)
> IndexError: pop from empty list`

After installing one mod manually by downloading the zip and restarting the server, the next attempt to install a mod through the mods_manager.py script completes successfully.

> python3 ./mods_manager.py -i LogisticTrainNetwork
Installing dependency "flib" version >= "0.6.0" for "LogisticTrainNetwork"
[==================================================]
Installed mod flib version 0.7.0 for Factorio version 1.1
A file already exists at the path "/storage/steam/factorio2/factorio/mods/LogisticTrainNetwork_1.15.7.zip" and is identical (same SHA1), skipping...

The mod configuration changed and Factorio need to be restarted in order to apply the changes.
Automatic reload has been disabled, please restart Factorio by yourself.
Finished !

**Comment by Tantrisse** [comment] 2021-03-25 10:47
Hi @kohbo,

Despite all my efforts, I cannot reproduce your problem...

Can you please tell me if:
- After installing the headless Factorio, did you started it ?
- Did you created / modified any files / folders in the Factorio install directory ?

By just looking at the error, it seems that your "mod-list.json" file in the Factorio install directory was empty (this should not happen, the "base" mod should always be here...)

**Comment by kohbo** [comment] 2021-03-25 13:59
@Tantrisse 

- I did create a new game and start the server after installing it. I then stopped the server before trying to install the mod.
- The only file I modified was the server-settings.json file. I did take a peek at mod-list.json when the exception was thrown and, at the time, the contents looked like this:

> {
  "mods":
    [
    ]
}

That was populated correctly after installing the first mod, like this:

>{
  "mods":
  [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "LogisticTrainNetwork",
      "enabled": true
    }
  ]
}

**Comment by Tantrisse** [comment] 2021-03-25 14:37
Okay thank you for these informations !

I've since did some tests myself and pushed an update which more thoroughly check the integrity of the `mod-list.json` file and the (sometimes clunky) behavior of the `base` mod.

This error should no longer appear, the script will warn you if the file is broken and correctly handle the presence (or not) of the `base` mod.

I'll close this issue as the problem is resolved but feel free to open it again if you encounter the same or a similar problem !
Thanks again,
Tantrisse.

**Closed as completed by Tantrisse** 2021-03-25 14:37 UTC
